FROM golang:1.16.9-alpine

WORKDIR /go/newsletter/

COPY go.mod go.sum main.go ./
COPY internal/ internal/
COPY sql/ sql/
COPY configuration/ configuration/

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o newsfeed

ENTRYPOINT ["./newsfeed"]
