version: "3.9"

services:
  db-test:
    image: postgres:14
    ports:
      - "5433:5432"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables_test.sql:/docker-entrypoint-initdb.d/fill_tables_test.sql
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "newsfeed"

  newsfeed-test:
    build:
      context: .
      dockerfile: Dockerfile_testing
    depends_on:
      - db-test
    ports:
      - "12345:12345"
    environment:
      - CONFIG_FILE_TEST_LOCATION=../../configuration/
      - CONFIG_FILE_TEST_NAME=config_test.yaml
      - DATABASE_HOST=db-test
